import { Router } from 'express';
import { z } from 'zod';
import { execute, queryAll, queryOne } from '../config/database.js';
import { requireRole } from '../middleware/auth.js';

const router=Router();
const text=z.string().trim().min(1).max(200); const id=z.coerce.number().int().positive();
const productSchema=z.object({loja_id:id,categoria_id:id,nome:text,descricao:z.string().max(1000).optional().default(''),preco_centavos:z.coerce.number().int().nonnegative(),estoque:z.coerce.number().int().nonnegative().default(0)});

router.get('/categorias',async(_req,res,next)=>{try{res.json({data:await queryAll('SELECT id,nome,descricao FROM categorias WHERE ativo=1 ORDER BY nome')});}catch(e){next(e)}});
router.post('/categorias',requireRole('ADMIN'),async(req,res,next)=>{try{const d=z.object({nome:text,descricao:z.string().max(500).optional()}).parse(req.body);await execute('INSERT INTO categorias(nome,descricao) VALUES(:nome,:descricao)',{':nome':d.nome,':descricao':d.descricao||null});res.status(201).json({message:'Categoria criada'});}catch(e){next(e)}});
router.get('/lojas',async(_req,res,next)=>{try{res.json({data:await queryAll('SELECT id,nome,descricao,endereco,cidade,estado,telefone,email FROM lojas WHERE ativo=1 ORDER BY nome')});}catch(e){next(e)}});
router.post('/lojas',requireRole('ADMIN'),async(req,res,next)=>{try{const d=z.object({nome:text,descricao:z.string().max(1000).optional(),endereco:z.string().max(300).optional(),cidade:z.string().max(100).optional(),estado:z.string().max(2).optional(),telefone:z.string().max(30).optional(),email:z.string().email().optional()}).parse(req.body);await execute('INSERT INTO lojas(nome,descricao,endereco,cidade,estado,telefone,email) VALUES(:nome,:descricao,:endereco,:cidade,:estado,:telefone,:email)',Object.fromEntries(Object.entries(d).map(([k,v])=>[`:${k}`,v??null])));res.status(201).json({message:'Loja criada'});}catch(e){next(e)}});
router.get('/produtos',async(req,res,next)=>{try{const search=String(req.query.search||'').trim();const cat=req.query.categoria_id?Number(req.query.categoria_id):null;const rows=await queryAll(`SELECT p.id,p.nome,p.descricao,p.preco_centavos,p.estoque,l.id loja_id,l.nome loja,c.id categoria_id,c.nome categoria FROM produtos p JOIN lojas l ON l.id=p.loja_id JOIN categorias c ON c.id=p.categoria_id WHERE p.ativo=1 AND l.ativo=1 AND (:search='' OR p.nome LIKE :like OR p.descricao LIKE :like) AND (:cat IS NULL OR p.categoria_id=:cat) ORDER BY p.nome`,{':search':search,':like':`%${search}%`,':cat':cat});res.json({data:rows});}catch(e){next(e)}});
router.post('/produtos',requireRole('ADMIN','OPERADOR'),async(req,res,next)=>{try{const d=productSchema.parse(req.body);if(!await queryOne('SELECT id FROM lojas WHERE id=:id AND ativo=1',{':id':d.loja_id}))return res.status(400).json({error:'Loja inválida'});if(!await queryOne('SELECT id FROM categorias WHERE id=:id AND ativo=1',{':id':d.categoria_id}))return res.status(400).json({error:'Categoria inválida'});await execute('INSERT INTO produtos(loja_id,categoria_id,nome,descricao,preco_centavos,estoque) VALUES(:loja,:cat,:nome,:desc,:preco,:estoque)',{':loja':d.loja_id,':cat':d.categoria_id,':nome':d.nome,':desc':d.descricao,':preco':d.preco_centavos,':estoque':d.estoque});res.status(201).json({message:'Produto criado'});}catch(e){next(e)}});
router.patch('/produtos/:id',requireRole('ADMIN','OPERADOR'),async(req,res,next)=>{try{const d=productSchema.partial().parse(req.body);const product=await queryOne('SELECT id FROM produtos WHERE id=:id',{':id':req.params.id});if(!product)return res.status(404).json({error:'Produto não encontrado'});const fields=Object.keys(d);if(!fields.length)return res.status(400).json({error:'Nenhum campo informado'});const allowed={loja_id:'loja_id',categoria_id:'categoria_id',nome:'nome',descricao:'descricao',preco_centavos:'preco_centavos',estoque:'estoque'};const sets=fields.map(k=>`${allowed[k]}=:${k}`).join(', ');const params=Object.fromEntries(fields.map(k=>[`:${k}`,d[k]]));params[':id']=req.params.id;await execute(`UPDATE produtos SET ${sets}, atualizado_em=CURRENT_TIMESTAMP WHERE id=:id`,params);res.json({message:'Produto atualizado'});}catch(e){next(e)}});
router.delete('/produtos/:id',requireRole('ADMIN'),async(req,res,next)=>{try{await execute('UPDATE produtos SET ativo=0, atualizado_em=CURRENT_TIMESTAMP WHERE id=:id',{':id':req.params.id});res.json({message:'Produto removido'});}catch(e){next(e)}});
export default router;
